# Generated by Django 3.2.5 on 2021-08-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
    ]
