# Generated by Django 3.2.5 on 2021-08-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_status_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('book_limit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.mode'),
        ),
    ]
