# Generated by Django 3.2.5 on 2021-09-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_mood_id_mode_mode_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
