# Generated by Django 3.2.5 on 2021-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('year_of_publish', models.DateField()),
                ('no_of_pages', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('author', models.CharField(max_length=100)),
                ('book_status', models.CharField(max_length=100)),
            ],
        ),
    ]
