# Generated by Django 3.2.5 on 2021-10-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('year_of_publish', models.DateField(blank=True, null=True)),
                ('no_of_pages', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('author', models.CharField(max_length=100)),
                ('book_status', models.CharField(default='Pending', max_length=100)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('book_type', models.CharField(default='Pending', max_length=100)),
                ('pdf', models.FileField(blank=True, default='images/not-available.png', null=True, upload_to='books')),
                ('audio', models.FileField(blank=True, default='images/not-available.png', null=True, upload_to='books')),
                ('book_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.mode')),
            ],
        ),
        migrations.CreateModel(
            name='DealVoucher',
            fields=[
                ('deal_voucher_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('wishlist_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.book')),
                ('wishlist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuickNote',
            fields=[
                ('QuickNote_id', models.AutoField(primary_key=True, serialize=False)),
                ('QuickNote_page_number', models.IntegerField()),
                ('QuickNote_text', models.TextField(blank=True, max_length=200, null=True)),
                ('QuickNote_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.book')),
                ('QuickNote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='DealVoucherUser',
            fields=[
                ('deal_voucher_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('valid_up_to', models.DateField()),
                ('deal_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.dealvoucher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.CharField(blank=True, max_length=200, null=True)),
                ('cart_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('cart_book', models.ManyToManyField(to='admin_dashboard.Book')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookmark_page_number', models.IntegerField()),
                ('bookmark_text', models.TextField(blank=True, max_length=200, null=True)),
                ('bookmark_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.book')),
                ('bookmark_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
