# Generated by Django 3.2.5 on 2021-08-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
