# Generated by Django 3.2.5 on 2021-09-22 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickNote',
            fields=[
                ('QuickNote_id', models.AutoField(primary_key=True, serialize=False)),
                ('QuickNote_page_number', models.IntegerField()),
                ('QuickNote_text', models.TextField(blank=True, max_length=200, null=True)),
                ('QuickNote_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.book')),
                ('QuickNote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
