# Generated by Django 3.2.5 on 2021-10-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_is_active'),
        ('admin_dashboard', '0002_quicknote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('wishlist_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.book')),
                ('wishlist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
