# Generated by Django 3.2.5 on 2021-08-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_book_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='images/not-available.png', upload_to='books'),
        ),
    ]
