# Generated by Django 3.2.5 on 2021-10-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_is_active'),
        ('admin_dashboard', '0003_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.CharField(blank=True, max_length=200, null=True)),
                ('cart_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('cart_book', models.ManyToManyField(to='admin_dashboard.Book')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
