# Generated by Django 3.2.5 on 2021-08-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_auto_20210821_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealvoucher',
            old_name='Description',
            new_name='description',
        ),
    ]
