# Generated by Django 3.2.5 on 2021-08-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_rename_description_dealvoucher_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealvoucheruser',
            old_name='deal_voucher_user',
            new_name='deal_voucher_user_id',
        ),
    ]
