# Generated by Django 3.2.5 on 2021-09-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_rename_deal_voucher_user_dealvoucheruser_deal_voucher_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='file',
            new_name='Pdf',
        ),
        migrations.AddField(
            model_name='book',
            name='audio',
            field=models.FileField(default='images/not-available.png', upload_to='books'),
        ),
    ]
