# Generated by Django 3.2.5 on 2021-09-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_auto_20210904_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Pdf',
            new_name='pdf',
        ),
    ]
