# Generated by Django 3.2.5 on 2021-09-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_alter_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audio',
            field=models.FileField(blank=True, default='images/not-available.png', null=True, upload_to='books'),
        ),
    ]
