# Generated by Django 3.2.5 on 2021-09-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_status'),
        ('admin_dashboard', '0010_alter_book_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookmark_page_number', models.IntegerField()),
                ('bookmark_text', models.TextField(blank=True, max_length=200, null=True)),
                ('bookmark_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.book')),
                ('bookmark_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
